apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: akakraft-managed-secret
  namespace: akakraft
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: staging
        secretsPath: /
  managedSecretReference:
    secretName: akakraft-secrets
    secretNamespace: akakraft
    creationPolicy: Orphan
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: google-calendar-managed-secret
  namespace: akakraft
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: staging
        secretsPath: /google-cal/
  managedSecretReference:
    secretName: google-calendar-secret
    secretNamespace: akakraft
    creationPolicy: Orphan
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cnpg-backup-managed-secret
  namespace: akakraft
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: staging
        secretsPath: /cnpg/
  managedSecretReference:
    secretName: cnpg-backup-secret
    secretNamespace: akakraft
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cnpg-db-credentials-managed-secret
  namespace: akakraft
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: staging
        secretsPath: /cnpg/db/  # username + password (gleicher Wert wie db-password unter /)
  managedSecretReference:
    secretName: akakraft-db-credentials
    secretNamespace: akakraft
    creationPolicy: Owner
