apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: akakraft-db-daily
  namespace: akakraft-prod
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: akakraft-db
  immediate: true
