apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: akakraft-managed-secret
  namespace: akakraft-prod
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft-prod
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: akakraft-secrets
    secretNamespace: akakraft-prod
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: google-calendar-managed-secret
  namespace: akakraft-prod
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft-prod
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: prod
        secretsPath: /google-cal/
  managedSecretReference:
    secretName: google-calendar-secret
    secretNamespace: akakraft-prod
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cnpg-backup-managed-secret
  namespace: akakraft-prod
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft-prod
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: prod
        secretsPath: /cnpg/
  managedSecretReference:
    secretName: cnpg-backup-secret
    secretNamespace: akakraft-prod
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cnpg-db-credentials-managed-secret
  namespace: akakraft-prod
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: akakraft-prod
      secretsScope:
        projectSlug: akakraft-online-h6-kr
        envSlug: prod
        secretsPath: /cnpg/db/
  managedSecretReference:
    secretName: akakraft-db-credentials
    secretNamespace: akakraft-prod
    creationPolicy: Owner
